name: "游냍 Reportar Bug"
description: Reportar un error que encontraste en el sistema.
title: "[BUG] - <descripci칩n corta>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Por favor llen치 esta plantilla para ayudarnos a reproducir el problema."

  - type: textarea
    id: description
    attributes:
      label: "Descripci칩n del bug"
      description: "Explic치 el comportamiento err칩neo que est치s viendo."
      placeholder: "Qu칠 ocurre, cu치ndo, c칩mo..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Pasos para reproducir"
      description: "Instrucciones para reproducir el bug"
      placeholder: |
        1. Ir a '...'
        2. Click en '...'
        3. Scroll hasta '...'
        4. Ver el error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Comportamiento esperado"
      description: "쯈u칠 esperabas que ocurriera?"
      placeholder: "..."
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: "Entorno"
      description: "Browser / OS / API / rama / dispositivo"
      placeholder: "Chrome 125, Android, staging, etc."
